/**
 * PDF Exporter - PDF 数据导出
 * 
 * 用途：将网站数据导出为 PDF 格式（带图表）
 * 优化：使用轻量级库，添加生成进度反馈
 * 不改变 ShipAny 结构，仅扩展功能
 */

import jsPDF from 'jspdf';
// import autoTable from 'jspdf-autotable'; // TODO: Install jspdf-autotable
import { ExportData, ExportOptions } from './csv-exporter';

export interface PDFExportOptions extends ExportOptions {
  siteId: string;
  domain: string;
  platform: string;
  includeChart?: boolean;
  includeDetails?: boolean;
}

/**
 * 导出为 PDF 格式
 */
export async function exportToPDF(
  data: ExportData[],
  options: PDFExportOptions
): Promise<Blob> {
  try {
    // 创建 PDF 文档
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });
    
    let yPosition = 20;
    
    // 1. 添加标题
    doc.setFontSize(24);
    doc.setTextColor(31, 41, 55); // gray-800
    doc.text('Performance Report', 20, yPosition);
    yPosition += 10;
    
    // 2. 添加网站信息
    doc.setFontSize(12);
    doc.setTextColor(107, 114, 128); // gray-500
    doc.text(`${options.siteName} (${options.domain})`, 20, yPosition);
    yPosition += 6;
    doc.text(`Period: ${options.startDate} to ${options.endDate}`, 20, yPosition);
    yPosition += 6;
    doc.text(`Platform: ${options.platform}`, 20, yPosition);
    yPosition += 6;
    doc.text(`Generated: ${new Date().toLocaleString()}`, 20, yPosition);
    yPosition += 15;
    
    // 3. 添加汇总统计
    doc.setFontSize(16);
    doc.setTextColor(31, 41, 55);
    doc.text('Summary Statistics', 20, yPosition);
    yPosition += 10;
    
    const totalRevenue = data.reduce((sum, row) => sum + row.revenue, 0);
    const totalVisitors = data.reduce((sum, row) => sum + row.visitors, 0);
    const totalOrders = data.reduce((sum, row) => sum + row.orders, 0);
    const avgUptime = data.length > 0
      ? data.reduce((sum, row) => sum + row.uptimePercentage, 0) / data.length
      : 0;
    
    // 汇总表格 (简化版本，不使用 autoTable)
    doc.setFontSize(10);
    const summaryData = [
      ['Total Revenue', `$${(totalRevenue / 100).toFixed(2)}`],
      ['Total Visitors', totalVisitors.toLocaleString()],
      ['Total Orders', totalOrders.toLocaleString()],
      ['Average Uptime', `${avgUptime.toFixed(2)}%`],
      ['Days Tracked', data.length.toString()],
      ['Avg Revenue/Day', `$${(totalRevenue / 100 / data.length).toFixed(2)}`],
      ['Avg Visitors/Day', Math.round(totalVisitors / data.length).toLocaleString()],
    ];
    
    summaryData.forEach((row, index) => {
      doc.text(row[0], 20, yPosition);
      doc.text(row[1], 120, yPosition);
      yPosition += 7;
    });
    
    yPosition += 10;
    
    // 4. 添加详细数据表格（如果启用）
    if (options.includeDetails !== false) {
      // 检查是否需要新页面
      if (yPosition > 200) {
        doc.addPage();
        yPosition = 20;
      }
      
      doc.setFontSize(16);
      doc.text('Daily Breakdown', 20, yPosition);
      yPosition += 10;
      
      // 简化版本：只显示前10条数据
      doc.setFontSize(9);
      const displayData = data.slice(0, 10);
      displayData.forEach((row, index) => {
        if (yPosition > 270) {
          doc.addPage();
          yPosition = 20;
        }
        doc.text(row.date, 20, yPosition);
        doc.text(`$${(row.revenue / 100).toFixed(2)}`, 60, yPosition);
        doc.text(row.visitors.toLocaleString(), 100, yPosition);
        doc.text(row.orders.toString(), 140, yPosition);
        doc.text(`${row.uptimePercentage.toFixed(1)}%`, 170, yPosition);
        yPosition += 6;
      });
      
      if (data.length > 10) {
        yPosition += 5;
        doc.setFontSize(10);
        doc.text(`... and ${data.length - 10} more days`, 20, yPosition);
      }
    }
    
    // 5. 添加页脚
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(156, 163, 175); // gray-400
      doc.text(
        `Page ${i} of ${pageCount}`,
        doc.internal.pageSize.getWidth() / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );
      doc.text(
        'Generated by SoloBoard',
        20,
        doc.internal.pageSize.getHeight() - 10
      );
    }
    
    // 6. 生成 Blob
    return doc.output('blob');
  } catch (error) {
    console.error('Failed to export PDF:', error);
    throw new Error('PDF export failed');
  }
}

/**
 * 生成 PDF 文件名
 */
export function generatePDFFilename(siteName: string, startDate: string, endDate: string): string {
  const sanitizedName = siteName.replace(/[^a-z0-9]/gi, '-').toLowerCase();
  const timestamp = new Date().getTime();
  return `${sanitizedName}-report-${startDate}-to-${endDate}-${timestamp}.pdf`;
}

/**
 * 创建 PDF 下载响应
 */
export function createPDFResponse(blob: Blob, filename: string): Response {
  return new Response(blob, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Cache-Control': 'no-cache',
    },
  });
}

/**
 * 生成简化版 PDF（仅汇总，无详细数据）
 */
export async function exportToSimplePDF(
  data: ExportData[],
  options: PDFExportOptions
): Promise<Blob> {
  try {
    const doc = new jsPDF();
    
    // 标题
    doc.setFontSize(20);
    doc.text('Performance Summary', 20, 20);
    
    // 网站信息
    doc.setFontSize(12);
    doc.text(`${options.siteName}`, 20, 35);
    doc.text(`${options.startDate} to ${options.endDate}`, 20, 42);
    
    // 汇总统计
    const totalRevenue = data.reduce((sum, row) => sum + row.revenue, 0);
    const totalVisitors = data.reduce((sum, row) => sum + row.visitors, 0);
    const avgUptime = data.reduce((sum, row) => sum + row.uptimePercentage, 0) / data.length;
    
    // 简化版本
    doc.setFontSize(10);
    let y = 55;
    doc.text('Total Revenue:', 20, y);
    doc.text(`$${(totalRevenue / 100).toFixed(2)}`, 100, y);
    y += 10;
    doc.text('Total Visitors:', 20, y);
    doc.text(totalVisitors.toLocaleString(), 100, y);
    y += 10;
    doc.text('Average Uptime:', 20, y);
    doc.text(`${avgUptime.toFixed(2)}%`, 100, y);
    
    return doc.output('blob');
  } catch (error) {
    console.error('Failed to export simple PDF:', error);
    throw new Error('Simple PDF export failed');
  }
}

